const colors = {
  dark: {
    background: "#0B0B12",
    foreground: "#FFFFFF",
    card: "#161622",
    cardForeground: "#FFFFFF",
    primary: "#00F0FF", // Neon cyan
    primaryForeground: "#000000",
    secondary: "#1F1F2E",
    secondaryForeground: "#FFFFFF",
    muted: "#1F1F2E",
    mutedForeground: "#8F8F9D",
    accent: "#8A2BE2", // Violet
    accentForeground: "#FFFFFF",
    destructive: "#FF3366",
    destructiveForeground: "#FFFFFF",
    success: "#00C896", // Green — save / download confirmations
    successForeground: "#FFFFFF",
    action: "#FF8C00", // Warm orange — primary conversion CTAs
    actionForeground: "#FFFFFF",
    premium: "#FFD700", // Gold — Pro / upgrade
    premiumForeground: "#0B0B12",
    border: "#2A2A3C",
    input: "#161622",
    gradientStart: "#00F0FF",
    gradientEnd: "#8A2BE2",
    actionGradientStart: "#FFB347",
    actionGradientEnd: "#FF6A00",
    premiumGradientStart: "#FFE066",
    premiumGradientEnd: "#FFAA00",
  },
  light: {
    background: "#F8F8FA",
    foreground: "#0B0B12",
    card: "#FFFFFF",
    cardForeground: "#0B0B12",
    primary: "#8A2BE2",
    primaryForeground: "#FFFFFF",
    secondary: "#EAEAF0",
    secondaryForeground: "#0B0B12",
    muted: "#EAEAF0",
    mutedForeground: "#6E6E7B",
    accent: "#00F0FF",
    accentForeground: "#0B0B12",
    destructive: "#FF3366",
    destructiveForeground: "#FFFFFF",
    success: "#00A878",
    successForeground: "#FFFFFF",
    action: "#EA580C",
    actionForeground: "#FFFFFF",
    premium: "#D4A300",
    premiumForeground: "#FFFFFF",
    border: "#D4D4DC",
    input: "#FFFFFF",
    gradientStart: "#8A2BE2",
    gradientEnd: "#00F0FF",
    actionGradientStart: "#FB923C",
    actionGradientEnd: "#EA580C",
    premiumGradientStart: "#F5C400",
    premiumGradientEnd: "#B87E00",
  },
  radius: 12,
};

export default colors;
